import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import {
  IonContent,
  IonHeader,
  IonTitle,
  IonImg,
  IonInput,
  IonItem,
  IonSelect,
  IonList,
  IonSelectOption,
  IonButton,
  IonToolbar,
  IonBackButton,
  IonCheckbox,
  IonAccordion,
  IonAccordionGroup,
  IonIcon,
  IonCard,
  IonCardHeader,
  IonCardContent,
  IonCardTitle,
  IonLabel,
  IonSpinner,
  IonModal,
  IonTextarea,
  IonBadge,
} from '@ionic/angular/standalone';

@NgModule({
  imports: [
    CommonModule,
    IonBadge,
    FormsModule,
    IonContent,
    IonHeader,
    IonTitle,
    IonImg,
    IonInput,
    IonItem,
    IonSelect,
    IonList,
    IonSelectOption,
    IonButton,
    IonToolbar,
    IonBackButton,
    IonCheckbox,
    IonAccordion,
    IonAccordionGroup,
    IonIcon,
    IonCard,
    IonCardHeader,
    IonCardContent,
    IonCardTitle,
    IonLabel,
    IonSpinner,
    IonModal,
    IonTextarea,
  ],
  exports: [
    CommonModule,
    FormsModule,
    IonContent,
    IonHeader,
    IonTitle,
    IonImg,
    IonInput,
    IonItem,
    IonSelect,
    IonList,
    IonSelectOption,
    IonButton,
    IonToolbar,
    IonBackButton,
    IonCheckbox,
    IonAccordion,
    IonAccordionGroup,
    IonIcon,
    IonCard,
    IonCardHeader,
    IonCardContent,
    IonCardTitle,
    IonLabel,
    IonSpinner,
    IonModal,
    IonTextarea,
    IonBadge,
  ],
})
export class SharedIonicModule {}
